### PR TITLE
Add Footer Component + Edit AboutUs page + Fixing Bugs of Login

### LINKED ISSUE #9: Add Footer Component + Edit AboutUs page + Fixing Bugs of Login
### Requirements:
- [x] Shrinking Footer
- [x] Redesign Footer’s color and padding
- [x] Changing the color to #aacaef tho hehe so it matches the same shade of blue
- [x] Change border-radius of Mission Card so it’s rounder?
- [x] Using font-weight 900 for MISSION, WHO WE ARE and font-weight 600 for Boost Productivity, etc. to ensure universality of fontface for elements (the higher level (title, heading) the bolder)
- [x] Changing WHO WE ARE to IDENTIFY
- [x] Compressing “At Productify…” horizontally so it doesn’t stretch as much throughout the page
- [x] In Simplify Task Management, the word “cracks” is on another line on its own. please play around with font size so that every line is filled by at least half the line (i.e. there should be no line with a single word).
- [x] Adding more space and padding between 2 content divs
- [x] Using “in” instead of “at” the United States.
- [x] Change font-family in footer to Montserrat.
- [x] For Coding style: in general it looks all good. But I think you should add more comments to describe your code and make it more readable.
- [x] Fixing bugs of Log In (Fix the Swapping Username and Email Bug)
- [x] Finding a new bug that in generateToken() function**

### Dependencies:
- backend/Controllers/User.js (Comment the generateToken() function so login can work)
- frontend/public/index.html (Add icon library)
- frontend/src/App.js (Add AboutUs route)
- frontend/src/components/Aboutus (Add Div1.jsx, Div1.module.css, Div2.jsx, Div2.module.css, MissionCard.jsx, MissionCard.module.css
- frontend/src/components/Footer
- frontend/src/service/user.js (Fix bug that relate to swapping username and email)

### Done requirements:
- 05/28/2023

https://github.com/viettech-group3/productify/assets/122703392/0aa50181-ee33-40dd-8468-dd000b0b671d

### PR DESCRIPTION
**Pull request by PhuocOng**
Hi everyone, I just created AboutUs page and Footer.jsx for FrontEnd. In the short term, AboutUs page and Home page are quite interchangeable, so in the future, if needed, I can combine both pages into 1 as well. I will send the video below for everyone to comment, thank you!

- [x] Shrinking Footer
- [x] Redesign Footer’s color and padding
- [x] Changing the color to #aacaef tho hehe so it matches the same shade of blue
- [x] Change border-radius of Mission Card so it’s rounder?
- [x] Using font-weight 900 for MISSION, WHO WE ARE and font-weight 600 for Boost Productivity, etc. to ensure universality of fontface for elements (the higher level (title, heading) the bolder)
- [x] Changing WHO WE ARE to IDENTIFY
- [x] Compressing “At Productify…” horizontally so it doesn’t stretch as much throughout the page
- [x] In Simplify Task Management, the word “cracks” is on another line on its own. please play around with font size so that every line is filled by at least half the line (i.e. there should be no line with a single word).
- [x] Adding more space and padding between 2 content divs
- [x] Using “in” instead of “at” the United States.
- [x] Change font-family in footer to Montserrat.
- [x] For Coding style: in general it looks all good. But I think you should add more comments to describe your code and make it more readable.
**- [ ] Fixing bugs of Log In (Fix the Swapping Username and Email Bug)
- [x] Finding a new bug that in generateToken() function**

https://github.com/viettech-group3/productify/assets/122703392/8198cdb0-16ed-4649-b769-8d66fba3bbf0

### CODE REVIEW

**Review by deidaraiorek — COMMENTED** [review]
Hi Phuoc, 

On my personal viewpoint, I believe the footer is too large. I think would be better if you can reduce the margin or padding. Moreover, I also believe that we can totally remove the About Us element in Header and combine your page with homage, since overall, the two pages have similar content.

In conclusion, this is great work! It is totally visually appealing and amazing. :3 Thank you :3

**Comment by lhoang25** [comment]
quá là mê luôn!! some minor suggestions của Trúc: 

1. lovely layout, super organized and easy for users to follow!
2. love the use of small icons! (nitpicking: can we change the color to #aacaef tho hehe so it matches the same shade of blue)
3. very nitpicking: do you wanna change border-radius so it’s rounder? in UX rounder containers provide a softer and more friendly feel compared to strictly rectangular boxes (which feel more formal; also, the Google Calendar launch page uses a bunch of rounder boxes so we would wanna ensure a sense of familiarity for our users who are used to Ggl Calendar as well). you can refer to the border-radius of the login/signup in Home page or play around to see what works.
4. consider changing title to bold font: use font-weight 900 for MISSION, WHO WE ARE and font-weight 600 for Boost Productivity, etc. to ensure universality of fontface for elements (the higher level (title, heading) the bolder). think about what you want users to see first when they open the page.
5. i’m a big fan of the hovering effects! so intuitive and user-friendly! i added animation for the title in Home page (so it flies in from the left when we first open the page) so later on if we merge Home page and About Us page we can add this animation too.
6. consider changing MISSION to WHAT WE DO so it follows the same subject-object sentence structure. vice versa, can change WHO WE ARE to TEAM or whatever so they’re both nouns.
7. consider compressing “At Productify…” horizontally so it doesn’t stretch as much throughout the page. sentences that take up a significant amount of horizontal space are harder to keep users’ attention while reading. maybe keep their max-width to 800 or something.
8. in Simplify Task Management, the word “cracks” is on another line on its own. please play around with font size so that every line is filled by at least half the line (i.e. there should be no line with a single word).
9. does the WHO ARE WE div currently cover the whole viewport? maybe consider adding padding between the end of MISSION and the beginning of content in the WHO ARE WE div (i.e. move the text WHO ARE WE and the image lower). space it out so users don’t feel cramped since we have lots of info there. nitpicking: there should at least be as much space from the end of the blue gradient background to WHO ARE WE as from WHO ARE WE to “Productify…”
10. i’m in love with this div’s two part structure (text on the left and image on the right)! 
11. use “in” instead of “at” the United States.
12. consider rewriting the 3 bullet points so it follows the same sentence structure (i.e. we are tech enthusiasts…, we are driven…, we are innovators) or anything that you find fitting.
13. change font-family in footer to Montserrat.
14. as Dang commented, maybe consider reducing padding-bottom or margin-bottom of footer just a bit.

overall lovely lovely lovely work! thanks for your efforts Phước!

**Comment by PhuocOng** [comment]
> quá là mê luôn!! some minor suggestions của Trúc:
> 
> 1. lovely layout, super organized and easy for users to follow!
> 2. love the use of small icons! (nitpicking: can we change the color to #aacaef tho hehe so it matches the same shade of blue)
> 3. very nitpicking: do you wanna change border-radius so it’s rounder? in UX rounder containers provide a softer and more friendly feel compared to strictly rectangular boxes (which feel more formal; also, the Google Calendar launch page uses a bunch of rounder boxes so we would wanna ensure a sense of familiarity for our users who are used to Ggl Calendar as well). you can refer to the border-radius of the login/signup in Home page or play around to see what works.
> 4. consider changing title to bold font: use font-weight 900 for MISSION, WHO WE ARE and font-weight 600 for Boost Productivity, etc. to ensure universality of fontface for elements (the higher level (title, heading) the bolder). think about what you want users to see first when they open the page.
> 5. i’m a big fan of the hovering effects! so intuitive and user-friendly! i added animation for the title in Home page (so it flies in from the left when we first open the page) so later on if we merge Home page and About Us page we can add this animation too.
> 6. consider changing MISSION to WHAT WE DO so it follows the same subject-object sentence structure. vice versa, can change WHO WE ARE to TEAM or whatever so they’re both nouns.
> 7. consider compressing “At Productify…” horizontally so it doesn’t stretch as much throughout the page. sentences that take up a significant amount of horizontal space are harder to keep users’ attention while reading. maybe keep their max-width to 800 or something.
> 8. in Simplify Task Management, the word “cracks” is on another line on its own. please play around with font size so that every line is filled by at least half the line (i.e. there should be no line with a single word).
> 9. does the WHO ARE WE div currently cover the whole viewport? maybe consider adding padding between the end of MISSION and the beginning of content in the WHO ARE WE div (i.e. move the text WHO ARE WE and the image lower). space it out so users don’t feel cramped since we have lots of info there. nitpicking: there should at least be as much space from the end of the blue gradient background to WHO ARE WE as from WHO ARE WE to “Productify…”
> 10. i’m in love with this div’s two part structure (text on the left and image on the right)!
> 11. use “in” instead of “at” the United States.
> 12. consider rewriting the 3 bullet points so it follows the same sentence structure (i.e. we are tech enthusiasts…, we are driven…, we are innovators) or anything that you find fitting.
> 13. change font-family in footer to Montserrat.
> 14. as Dang commented, maybe consider reducing padding-bottom or margin-bottom of footer just a bit.
> 
> overall lovely lovely lovely work! thanks for your efforts Phước!



> quá là mê luôn!! some minor suggestions của Trúc:
> 
> 1. lovely layout, super organized and easy for users to follow!
> 2. love the use of small icons! (nitpicking: can we change the color to #aacaef tho hehe so it matches the same shade of blue)
> 3. very nitpicking: do you wanna change border-radius so it’s rounder? in UX rounder containers provide a softer and more friendly feel compared to strictly rectangular boxes (which feel more formal; also, the Google Calendar launch page uses a bunch of rounder boxes so we would wanna ensure a sense of familiarity for our users who are used to Ggl Calendar as well). you can refer to the border-radius of the login/signup in Home page or play around to see what works.
> 4. consider changing title to bold font: use font-weight 900 for MISSION, WHO WE ARE and font-weight 600 for Boost Productivity, etc. to ensure universality of fontface for elements (the higher level (title, heading) the bolder). think about what you want users to see first when they open the page.
> 5. i’m a big fan of the hovering effects! so intuitive and user-friendly! i added animation for the title in Home page (so it flies in from the left when we first open the page) so later on if we merge Home page and About Us page we can add this animation too.
> 6. consider changing MISSION to WHAT WE DO so it follows the same subject-object sentence structure. vice versa, can change WHO WE ARE to TEAM or whatever so they’re both nouns.
> 7. consider compressing “At Productify…” horizontally so it doesn’t stretch as much throughout the page. sentences that take up a significant amount of horizontal space are harder to keep users’ attention while reading. maybe keep their max-width to 800 or something.
> 8. in Simplify Task Management, the word “cracks” is on another line on its own. please play around with font size so that every line is filled by at least half the line (i.e. there should be no line with a single word).
> 9. does the WHO ARE WE div currently cover the whole viewport? maybe consider adding padding between the end of MISSION and the beginning of content in the WHO ARE WE div (i.e. move the text WHO ARE WE and the image lower). space it out so users don’t feel cramped since we have lots of info there. nitpicking: there should at least be as much space from the end of the blue gradient background to WHO ARE WE as from WHO ARE WE to “Productify…”
> 10. i’m in love with this div’s two part structure (text on the left and image on the right)!
> 11. use “in” instead of “at” the United States.
> 12. consider rewriting the 3 bullet points so it follows the same sentence structure (i.e. we are tech enthusiasts…, we are driven…, we are innovators) or anything that you find fitting.
> 13. change font-family in footer to Montserrat.
> 14. as Dang commented, maybe consider reducing padding-bottom or margin-bottom of footer just a bit.
> 
> overall lovely lovely lovely work! thanks for your efforts Phước!


Damnnn =)))) Comment không thể tuyệt vời hơn. Appreciate công sức m comment hehe =))))

**Review by hoatuyet423 — COMMENTED** [review]
The UI in general looks really awesome! I just have some small thoughts:
1. Maybe make the description in the Mission part with bigger size or bold it, since it is kinda hard to see as it is blended in with the background colors right now. 
2. I agree with Truc and Dei that the padding and margin need to be fixed 
3. I also feel like the font/boldness of the nav bar is a bit off with the general looks. Like the words in the nav bar is pretty fat compared to the websites words in general lol.
4. The hovering features is so cool!!!
For Coding style: in general it looks all good. But I think you should add more comments to describe your code and make it more readable.

**Review by lhoang25 — APPROVED** [review]

**Pull request merged**
